- "Proceedings Chair: SIGMOD/PODS 2020, ICDT 2021"
- "Area Chair: ICML 2022/2023/2024, NeurIPS 2022/2023, ICLR 2023/2024, TheWebConf 2023"
- "PC Member: NeurIPS 2021, ICML 2021, KDD 2021, VLDB 2020, ICDE 2021, SIGMETRICS 2020, ICBK 2019, NDBC 2018, ICLR 2023, ICDE 2023"
- "Conference Reviewer: SODA, ISAAC, VLDB, ICDE, CIKM, PODS, SIGMOD, KDD"
- "Journal Reviewer: TKDE, TODS, VLDBJ, TOIS, SICOMP, TALG, GEOINFORMATICA, TNNLS, TPAMI"
- "Member of Journal Editorial Board: IEEE TPAMI Associate Editor, FCS Young Editor"
- "Members: 中国计算机学会数据库专委会专委，中国计算机学会学术工作委员会委员，<a href=\"https://en.pazhoulab.com\">人工智能与数字经济广东省实验室（琶洲实验室）</a>青年科学家"